### ISSUE TITLE
Task #2: Tabel

### ISSUE THREAD

**Issue by fadamsyah** [fadamsyah/longitudinal-control-based-nature-inspired-optimization#2]
- [x] Masukin tabel ke Manuscript sesuai format
- [x] Nge-refer tabel di manuscript
- [x] Masukin data dari hasil simulasi PSO yang baru (nanti)
- [x] Ngerapihin Table 4 yang panjang

[Reference](https://journal.ump.edu.my/ijame/manuscript)

**Comment by fadamsyah** [comment]
Untuk yang nge-refer tabel, cek dulu formatnya, apakah dia pake hyperlink atau dinomorin manual. Nanti kita nyesuaiin format nya aja ya

**Comment by fadamsyah** [comment]
@karinaardellia @Vermillord Table 4 itu sebenernya perlu ngga ya? Panjang banget soalnya. Lebih baik seperti itu atau kita singkat kira-kira, kayak begini

- Accuracy (min, max, mean)
- MSE (min, max, mean)
- MAER (min, max, mean)

**Comment by Vermillord** [comment]
Itu kan buat nunjukin Acc, MSE, MAER dari setiap data hasil MFPA kan ya. Kayak gitu kayaknya bisa juga atau semisal emg mau nunjukkin kalo untuk setiap dataset hasilnya MFPA itu bagu berarti gpp nunjukkin smuanya tapi dibuat manjang aja, dibagi dua data 1-12 di bagian kiri trus data 12-24 di bagian kanan

**Comment by fadamsyah** [comment]
Nah eta @Vermillord, masalahnya kita perlu nunjukin setiap Acc, MSE, MAER untuk masing2 dataset 1 2 3 4 ... itu ngga ya? Btw bener juga ide terkait tabel yang dibagi dua wkwkwk

**Comment by Vermillord** [comment]
Kalo perlu apa engga, sebenernya sedetil apa perlu diliatin performa dari algoritmanya sih wkwkwk. Mungkin @karinaardellia ada pendapat

**Comment by fadamsyah** [comment]
@Vermillord Lif maaf Aku kurang nangkep wkkwkw

**Comment by Vermillord** [comment]
Tujuan dari nunjukin tabelnya kan buat tau si MFPA punya performa kayak gimana untuk setiap dataset. Nah menurutku sih, masalah mau ngelampirin keseluruhan 24 data atau rata2nya aja itu tergantung dari kitanya juga mau seberapa ngeliatinnya.

Kalo misalkan keseluruhan 24 data ditunjukkin berarti emg pengen ngeliatin kalo MFPA ini bisa ngehasilin output yang baik dan berlaku untuk data2 yang berbeda.

Kalo misalkan rata2nya aja berarti kan cuma sekedar ngasih tau kalo MFPA itu punya performa yang baik tanpa memerhatikan distribusi output yang dihasilin untuk setiap data.

Menurut aku sih gitu wkwkkwkw, maap kalo rada ribet nulisnya

**Comment by fadamsyah** [comment]
Wkwkwk mantap lip. Sabi-sabi, soalnya kita angkat topik tentang modelling juga ya. Aku coba klarifikasi beberapa hal yoo

- Saat training model dengan MFPA, seluruh 24 data itu _dijadiin satu_, jadi training nya bareng [(link)](https://github.com/fadamsyah/longitudinal-control-based-nature-inspired-optimization/blob/master/sys_id/fpa/System%20Identification.ipynb), bukan 1 dataset = 1 x training MFPA
- Untuk _"MFPA ini bisa ngehasilin output yang baik dan berlaku untuk data2 yang berbeda."_. Menurut ku ini yang lebih tepatnya adalah poin tentang si **model** yang kita propose lif.
- Saksi bahasannya tu MFPA **lebih unggul** di banding algoritma yang lain, dan model nya bisa **merepresentasikan** sistem dengan baik

**Comment by fadamsyah** [comment]
Jadi kesimpulannya berarti kita tetep include aja tabelnya ya. In case ternyata reviewer minta ditampilin plot untuk masing2 data latih, nanti kita tambahin di appendix (kalau ada). Gini bukan ya? Wkwkwkw

**Comment by karinaardellia** [comment]
keknya mending bagi dua tabel nya kak

**Comment by Vermillord** [comment]
Iyes mending gitu aja, bagi tabelnya jadi horizontal trus kalo emg perlu tampilin plot berarti masuk appendix aja

**Comment by fadamsyah** [comment]
Alhamdulillah Table udah @Vermillord @karinaardellia

**Comment by fadamsyah** [comment]
Alhamdulillah Table udah @Vermillord @karinaardellia
