### ISSUE TITLE
Task #3: Equation

### ISSUE THREAD

**Issue by fadamsyah** [fadamsyah/longitudinal-control-based-nature-inspired-optimization#3]
- [x] Masukin semua equation ke manuskrip (ada beberapa yang belum)
- [x] Cek penomoran equation, sudah urut & betul apa belum
- [x] Nge-refer equation di manuskrip

[Reference](https://journal.ump.edu.my/ijame/manuscript)

**Comment by fadamsyah** [comment]
Untuk yang nge-refer equation, cek dulu formatnya, apakah dia pake hyperlink atau dinomorin manual. Nanti kita nyesuaiin format nya aja ya

**Comment by fadamsyah** [comment]
@Vermillord Equation 3 udah lif?

**Comment by fadamsyah** [comment]
@Vermillord @karinaardellia equation udah semua, tapi belum _di-**refer**_

**Comment by karinaardellia** [comment]
oke kak siap, coba dilengkapi

**Comment by fadamsyah** [comment]
Refer equation udah rin @karinaardellia ? Kalau udah, issue ini tolong di-close yak. Nuhun pisannnn

**Comment by karinaardellia** [comment]
oh oke kak
