### ISSUE TITLE
Task #4: Figure

### ISSUE THREAD

**Issue by fadamsyah** [fadamsyah/longitudinal-control-based-nature-inspired-optimization#4]
- [x] Cek figure, apakah ada figure yang _redundant_ atau ga terlalu penting. Manuskrip-nya semakin singkat, semakin bagus
- [x] Masukin figure ke manuskrip
- [x] Nge-refer gambar di manuskrip

[Reference](https://journal.ump.edu.my/ijame/manuscript)

**Comment by fadamsyah** [comment]
Untuk yang nge-refer gambar, cek dulu formatnya, apakah dia pake hyperlink atau dinomorin manual. Nanti kita nyesuaiin format nya aja ya

**Comment by fadamsyah** [comment]
@Vermillord @karinaardellia Gambar yang **stability test** signifikan ngga ya, takutnya redundan sama tabel **stability comparison**? Atau edit tabel **stability comparison** dengan cantumin (min_cost, max_cost, mean_cost, variance)?

Sebenernya gambar **stability test** ini menarik si, dan jauh lebih intuitif daripada tabel **stability comparison** wkwkwk. Tapi isu yang kupikirin sebenernya takut kepanjangan aja papernya, kecuali kita bisa nempatin gambar dengan rapih dan pas.

Mangga kalau ada pendapatttt

**Comment by Vermillord** [comment]
Kayaknya mendingan gambar drpd tabel sih kalo menurut aku, cuma tadi ditambahin min, max, mean, sama varnya sabi bet biar lebih informatif lagi gacuma gambar pembanding aja

**Comment by fadamsyah** [comment]
@Vermillord Okeeeee

**Comment by Vermillord** [comment]
Fig. 3 b sama c perlu digabung jadi satu figure aja ga? Biar gaterlalu ngabisin space kalo ditaro tiga2nya dalam satu figure wkwkwk. Sisanya kayaknya gaada yg redundant. Cuma paling buat figure 5 sama 6 kira2 itu throttle perlu dipisah dari respon sama setpoint kah? Kayaknya bisa nyingkat semisal response, setpoint, sama throttle dalam satu grafik yang sama

**Comment by fadamsyah** [comment]
> Fig. 3 b sama c perlu digabung jadi satu figure aja ga? Biar gaterlalu ngabisin space kalo ditaro tiga2nya dalam satu figure wkwkwk. Sisanya kayaknya gaada yg redundant. Cuma paling buat figure 5 sama 6 kira2 itu throttle perlu dipisah dari respon sama setpoint kah? Kayaknya bisa nyingkat semisal response, setpoint, sama throttle dalam satu grafik yang sama

Sippp okee lip @Vermillord

**Comment by fadamsyah** [comment]
Btw, coba tolong masukin gambar2 yang lainnya dulu ya ke Word @Vermillord @karinaardellia , aku pengen tau apakah format gambar kita ada perlu di-edit apa ngga. Misal resolusinya kegedean jadi tulisannya jadi tipis, atau pecah, atau lain-lain

**Comment by Vermillord** [comment]
okee kak ntar dimasukin, btw gambarnya kan png sih harusnya ga berubah resolusinya

**Comment by fadamsyah** [comment]
> okee kak ntar dimasukin, btw gambarnya kan png sih harusnya ga berubah resolusinya

Setau ku, kalau di-resize, biasanya ada yang berubah dari _image_, karena dia pake di-interpolasi. Misal kalau tulisannya tipis, bisa jadi makin tipis pas image di-_resize_ jadi kecil

**Comment by Vermillord** [comment]
oh bener juga oke kak dicek deh besok

**Comment by Vermillord** [comment]
figure 1-4 udah masuk

**Comment by fadamsyah** [comment]
> figure 1-4 udah masuk

Mantapp, btw tolong sekalian di-replace ya lip yang figure 2-4

- Figure 2: [link](https://github.com/fadamsyah/longitudinal-control-based-nature-inspired-optimization/tree/master/ssr/Analysis/img)
- Figure 3: [link](https://github.com/fadamsyah/longitudinal-control-based-nature-inspired-optimization/tree/master/sys_id/Analysis/img)
- Figure 4: [link](https://github.com/fadamsyah/longitudinal-control-based-nature-inspired-optimization/tree/master/PID%20Tuning/Analysis/img) (`simulation_result.png`, `stability_check.png`)

**Comment by fadamsyah** [comment]
@Vermillord 
- Figure 5: [link](https://github.com/fadamsyah/longitudinal-control-based-nature-inspired-optimization/tree/master/PID%20Tuning/additional/cost0)

Figure 6 ntaran yak, aku istirahat dulu

**Comment by fadamsyah** [comment]
@Vermillord 

- Figure 6: [link](https://github.com/fadamsyah/longitudinal-control-based-nature-inspired-optimization/tree/master/PID%20Tuning/additional/img)

**Comment by fadamsyah** [comment]
@Vermillord figure 5 ada yang kebalik urutannya
