### ISSUE TITLE
Task #5: Daftar Pustaka

### ISSUE THREAD

**Issue by fadamsyah** [fadamsyah/longitudinal-control-based-nature-inspired-optimization#5]
- [x] Masukin daftar pustaka & refer

[Reference](https://journal.ump.edu.my/ijame/manuscript)

**Comment by fadamsyah** [comment]
@Vermillord @karinaardellia Aku liat-liat di Word udah ada Referensi. Apakah yang referensi ini hitungannya sudah selesai?

**Comment by karinaardellia** [comment]
belum kak ada beberapa paper yang belum nemu, aku selesaiin hari ini ya kak

**Comment by karinaardellia** [comment]
btw kak aku baru sadar, format sitasinya unik wkwkwk bukan IEEE setelah dilihat2. Jadinya gak bisa otomatis di mendeley. Ngakalinnya gimana yak? atau yaudah manual aja?

**Comment by fadamsyah** [comment]
> btw kak aku baru sadar, format sitasinya unik wkwkwk bukan IEEE setelah dilihat2. Jadinya gak bisa otomatis di mendeley. Ngakalinnya gimana yak? atau yaudah manual aja?

Seharusnya di dalam word nya ada format nya juga rin wkwkwk. Coba tolong dicari dulu menurut ku, kalau udh mentok banget, yaudah langsung manual aja wkwkwk

**Comment by karinaardellia** [comment]
kalau dicocokin sama format template word udah sama kak, masalahnya format template word sama web beda rada bingung harus ikut mana wkwkwk

**Comment by fadamsyah** [comment]
> kalau dicocokin sama format template word udah sama kak, masalahnya format template word sama web beda rada bingung harus ikut mana wkwkwk

Wkwkwkwk bisa begitu yak. Kayaknya coba liat paper yang udh di-published di journal itu rin

**Comment by karinaardellia** [comment]
oke siap kak

**Comment by karinaardellia** [comment]
ini harusnya juga udah kak, aku close yak
